services:
  discovery-service:
    #build: ./Discovery_Service
    image: mehdiben24/corail-discovery-service
    container_name: discovery-service
    ports:
      - "8762:8761"
    expose:
      - "8762"
    networks:
      - discovery-net

  gateway-service:
    #build: ./Gateway_Service
    image: mehdiben24/corail-gateway-service
    container_name: gateway-service
    ports:
      - "8888:8888"
    expose:
      - "8888"
    links:
      - discovery-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka
    depends_on:
      - discovery-service
    networks:
      - discovery-net
      - gateway-net

  auth-service:
    #build: ./Auth_Service
    image: mehdiben24/corail-auth-service
    container_name: auth-service
    ports:
      - "8081:8081"
    expose:
      - "8081"
    links:
      - discovery-service
      - gateway-service
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/corail_auth?createDatabaseIfNotExist=true
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka
      - minio.endpoint=http://minio:9000
    depends_on:
      - discovery-service
      - mysqldb
      - gateway-service
      - minio
    networks:
      - springapimysql-net
      - discovery-net
      - gateway-net
      - minio-auth

  core-service:
    #build: ./Core_Service
    image: mehdiben24/corail-core-service
    container_name: core-service
    ports:
      - "8082:8082"
    expose:
      - "8082"
    links:
      - discovery-service
      - gateway-service
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/corail_core?createDatabaseIfNotExist=true
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka
      - minio.endpoint=http://minio:9000
    depends_on:
      - gateway-service
      - discovery-service
      - mysqldb
      - minio
    networks:
      - springapimysql-net
      - discovery-net
      - gateway-net
      - minio-net

  mysqldb:
    container_name: mysqldb
    image: mysql
    ports:
      - "3307:3306"
    expose:
      - "3307"
    environment:
      MYSQL_DATABASE: corail
      MYSQL_HOST: localhost
      MYSQL_ALLOW_EMPTY_PASSWORD: ""
    networks:
      - springapimysql-net

  minio:
    image: bitnami/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DEFAULT_BUCKETS=corail
    networks:
      - minio-net
      - minio-auth



networks:
  springapimysql-net:
  discovery-net:
  gateway-net:
  minio-net:
  minio-auth:




